### ISSUE TITLE
Curious event..

### ISSUE THREAD

**Issue by 153957** [HiSPARC/pysparc#20]
Why did station 202 trigger for event [1432514377592294598](http://data.hisparc.nl/api/station/202/trace/1432514377592294598/?raw) (2015/5/25 0:39:37)

![trace_202_ 1432514377592294598](https://cloud.githubusercontent.com/assets/1433682/7831859/d93ff556-045a-11e5-9d61-2e8ebaa7b897.png)

Channel 2 only reached 212 ADC counts (pulseheight: 8).

**Comment by 153957** [comment]
Found the event with:

```python
data = tables.open_file('2015_5_25.h5', 'r')
ams = data.root.hisparc.cluster_amsterdam
min(sort(ams.station_202.events.col('pulseheights') + ams.station_202.events.col('baseline'))[:, 2])
```
- pulseheight + baseline gives highest ADC value reached by channel.
- `sort()` sorts the channels for each event, from low to high.
- then filter to get the 3rd value (column) from each event (e.g. 260 from: `[-1, -1, 260, 300]`)
- then get the min value from this list.

With the 2 low trigger each channel should be above the low threshold (253), so the lowest of the lower of the two should at least be 254. Possibly a bit less due to filtering of the traces..

**Comment by davidfokkema** [comment]
Interesting. I'll take a look, hopefully Monday.

**Comment by davidfokkema** [comment]
I checked for other stations, most notably a LabVIEW station (College Hageveld, 203). Event [1451956613516963433](http://data.hisparc.nl/api/station/203/trace/1451956613516963433/?raw) is also very curious. A pulseheight of only 2 ADC counts. I'm closing this for now. It seems that the hardware sporadically triggers on noise.
