### ISSUE TITLE
Wrong GPS configuration? Or wrong extended timestamps?

### ISSUE THREAD

**Issue by 153957** [HiSPARC/pysparc#22]
Jos (@josst) discovered that there were far fewer coincidences with other stations for stations that switched to PySPARC compared to the time before they switched.

Most notably station 102 which is close to two other stations (104 and 105). These normally have many coincidences, however, since the switch to PySPARC there have been hardly any. This may be caused by a mal configured GPS (perhaps UTC instead of GPS time, can be checked with `sapphire.Coincidences.search_coincidences` by using the 'shift' option.). Or perhaps calculating the ext_timestamp wrong, or at least differently from the HiSPARC DAQ..

**Comment by davidfokkema** [comment]
More info is needed. The station not only switched to PySPARC, it switched to HiSPARC III hardware, if I recall correctly. It is possible that the GPS was never correctly calibrated using a self-survey. We should also check the other stations to make really sure they are using GPS time. We should check the implementation of the timestamp calculation and check that with the LabVIEW code.

First step: finalising the GPS code for PySPARC, calibrating the GPS and checking for coincidences.

**Comment by 153957** [comment]
Quantization error was handled wrong (interpreted as seconds instead of nanoseconds).
This has been fixed. However, there is still exactly one second time difference between PySPARC and HiSPARC DAQ stations. It is not yet clear why this occurs.

**Comment by davidfokkema** [comment]
See #29

**Comment by 153957** [comment]
The second difference is 'accounted' for in ced06268052cff22424b9479608ab3adce25a59b. We have not (yet) found a cause for the error in the PySPARC code.

There may be an error in the HiSPARC DAQ (LabView). However, that will require further investigation. If the error is in the LabView DAQ it will be impractical to fix, because it is difficult to simultaneously update the DAQ on all HiSPARC stations. It might be better to keep the second offset in the data (well documented!!).

Note; this is also important when looking for coincidences data from other sources, e.g. lightning. @renaldo20

**Comment by renaldo20** [comment]
Merci Arne,

Hou me maar op de hoogte ivm coïncidenties met de KNMI-database

Hartelijke groeten
Reno (iPad)

**Comment by 153957** [comment]
@vaneijk has confirmed the 1 second offset is created in the LabView DAQ. For now we will also keep this 1 second offset in PySPARC, with documentation. We should leave this issue open for now because it is important to keep track of developments.

**Comment by davidfokkema** [comment]
We basically fixed this in ced06268052cff22424b9479608ab3adce25a59b. We have a question at #31, which is also resolved. I'll close this for now, although we still don't know *why* LabVIEW would do such a thing.

**Comment by 153957** [comment]
This +1 is required due to the order of things.
See https://github.com/HiSPARC/firmware/issues/2#issuecomment-181399798

**Comment by davidfokkema** [comment]
+1 for DS9 reference
