### ISSUE TITLE
Message from the future: blocking everything

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/pysparc#35]
If a one-second message is received from the future (probably a very bad GPS signal), it blocks all further processing. All correct one-second messages will appear to be out-of-order. That blocks everything.

**Comment by 153957** [comment]
(nice title :+1:)

**Comment by davidfokkema** [comment]
While I *do* like the title, the bug report is not very specific. For example, one-second messages are always stored and never blocked. This appears to be a duplicate of the much more specific #21.
