### ISSUE TITLE
New HiSPARC III firmware

### ISSUE THREAD

**Issue by 153957** [HiSPARC/pysparc#37]
A newer version of the HiSPARC firmware is available, currently [v20](https://github.com/HiSPARC/firmware/releases)
- Correct PMT current channels.
- Comparator now with 2.5 ns accuracy

(Note; A new version might be released soon to fix misaligned trace readout of partially overlapping events)

**Comment by davidfokkema** [comment]
Fixed in ee58a4883f338988821674b7166eb0f493aa58d2.
