### ISSUE TITLE
Fix config messages

### ISSUE THREAD

**Issue by 153957** [HiSPARC/pysparc#39]
The configs reported by the PySPARC stations are missing the trigger requirements.
i.e. the required number of low/high signals, wether it is and/or, and possible external trigger settings. 
http://data.hisparc.nl/show/source/trigger/102/
http://data.hisparc.nl/show/source/trigger/202/
http://data.hisparc.nl/show/source/trigger/599/

Normally such 2 detector stations have a '2' in the number of low signals required.
e.g. http://data.hisparc.nl/show/source/trigger/104/

See; #33

**Comment by 153957** [comment]
This will cause the processing of events to fail reconstructing the trigger time.
http://data.hisparc.nl/data/202/events/?download=False&start=2016-02-12+00%3A00%3A00&end=2016-02-12+00%3A05%3A00

Before yesterday the processing of events used trigger conditions based on the number of detectors;
http://data.hisparc.nl/data/202/events/?download=False&start=2016-02-11+00%3A00%3A00&end=2016-02-11+00%3A05%3A00

This example may fail to work once data for 11 Feb has been reanalysed..

**Comment by davidfokkema** [comment]
I'll fix this quickly.

**Comment by 153957** [comment]
Thanks, it does present a small problem for the existing configs.
To fix it, the raw data needs to be changed, setting the value '2' in the `trig_low_signals` column for the configs of those stations (since they were using PySPARC).

**Comment by davidfokkema** [comment]
So, a script must be written to retroactively update the configs?

**Comment by 153957** [comment]
Yea, a new migration script for the datastore, should not be to difficult.
Loop over all dates which have a config for those stations, then modify the `trig_low_signals` column to be 2.

Perhaps first filter to make sure it is only done for when PySPARC was used on those stations.. However, it seems they did not have other trigger settings, so that can be ignored.

**Comment by 153957** [comment]
Actually, the same has to happen for the reported PMT current, which should be in almost a factor 10 smaller. (#38).
And for the trigger windows.. #36..

**Comment by davidfokkema** [comment]
Do you want the `detnum` and `spare_bytes` properties included?

**Comment by 153957** [comment]
Not necessarily. The detnum from the HiSPARC DAQ is sometimes incorrect (when the station number in config.ini and HiSPARC DAQ don't match)

**Comment by davidfokkema** [comment]
The bugs are closed, the config messages are sent. The migration script is the only thing that remains.

**Comment by davidfokkema** [comment]
I believe this is fixed in hisparc/datastore@753bdaf23a8743718f39ddf1f19d72c48fced01f.

**Comment by 153957** [comment]
Almost, there appear to be a couple configs left for 599 and 102 that have not bee properly converted.
Maybe only the public db entry needs to be updated, or the raw configs were not modified;

See the high values in the PMT current graphs:
http://data.hisparc.nl/show/stations/599/config/
http://data.hisparc.nl/show/stations/102/config/

**Comment by davidfokkema** [comment]
In only start conversion on a specific date. That date was supposed to be when PySPARC started sending configurations. Alas, there are already configurations three days earlier.

**Comment by davidfokkema** [comment]
I lost my marbles. Will try to locate them in the morning.

**Comment by 153957** [comment]
Easily found like this:
http://data.hisparc.nl/admin/histograms/configuration/?source__station__number=102&mas_ch1_current__gt=25

http://data.hisparc.nl/admin/histograms/configuration/?source__station__number=599&mas_ch1_current__gt=25

**Comment by davidfokkema** [comment]
Oh, I found them! But now I need to run the script in the correct Python environment. I think I remember now; there is a conda environment on /data/hisparc, right? Unfortunately, Kaj Munk has a new firewall/web filtering policy since last week. I found out today that I can no longer use SSH or VPN. Also, Google Drive does not work anymore, but Dropbox *does*. Sigh.

**Comment by 153957** [comment]
```bash
PATH=/data/hisparc/env/miniconda/bin:$PATH
source activate hisparc
```

No ssh and VPN? even form the inside out (i.e. the PySPARC station can not setup VPN to tietar?)

**Comment by davidfokkema** [comment]
Because of port filtering issues in the past, we masked the VPN traffic as HTTPS, which is generally not blocked on schools. So, the PySPARC station is up and running, but the admin VPN network is unreachable. I've complained. I can't even send mail from my Nikhef address, because that needs a SMTPS connection with Nikhef. :angry:

**Comment by 153957** [comment]
Use your iPhone as a hotspot? probably not good for your data caps..

**Comment by tomkooij** [comment]
At least github allows SSH over HTTPS (port 443). So you can still use git ;) 
Too bad login.nikhef.nl does not allow port 443.

**Comment by davidfokkema** [comment]
I removed the configuration objects, and set the needs_update and needs_update_configs flags of the sources. I ran hisparc-update (still running) and it found lots and lots of new events for various stations on dates in february, january, ...? Any idea what may have caused this?

**Comment by davidfokkema** [comment]
Finished without problems. I verified that the new configurations are present, and that the graphs now look ok.
