### ISSUE TITLE
Silent hardware: event rate 1.4 Hz

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/pysparc#5]
In the case of hardware no longer sending events, the _latest_timestamp is never updated and the _event_rates are never drained.  We still have a trigger rate of 1.4 Hz for example, while there are no events being received.

**Comment by 153957** [comment]
Does this concern the Nagios status? Can't Nagios be configured to set the status to CRITICAL if it does not recieve an event rate update for some amount of time? Or does PySPARC continu to update the Nagios status even though no new events are coming in, in which case you should compare the latest_timestamp to the (UTC, corrected with leap seconds) clock.

**Comment by davidfokkema** [comment]
The latter. This is not particularly hard to do, but until it is done, this issue serves as a reminder.
